# Generated by Django 4.2.4 on 2024-09-02 20:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(default='', max_length=100)),
                ('station_code', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Train_no', models.IntegerField(default=0, unique=True)),
                ('Train_name', models.CharField(default='', max_length=100)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.IntegerField(default=0)),
                ('end_journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_journeys', to='railway.station')),
                ('start_journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_journeys', to='railway.station')),
            ],
        ),
    ]
