# Generated by Django 4.2.4 on 2024-09-02 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0002_alter_train_end_journey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_no_of_seats', models.IntegerField(default=0)),
                ('train_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_journeys', to='railway.train')),
            ],
        ),
    ]
